# main text of home
name: Yining Hong
bio: A Girl who travels the world playing the piano

# twitter summary info
description: A blog about technology and music and stuff related

picture: assets/images/credit_to_zeng.jpg

url: https://evelinehong.github.io/
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line

github: evelinehong
email: yninghong@gmail.com

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
future: true
